    server {

        return 301 https://r2s.fly.dev;

        listen 443 http2 ssl;
        server_name read2succeed.tk www.read2succeed.tk;
        root /usr/share/nginx/r2s;

        # disable caching
        add_header Last-Modified $date_gmt;
        add_header Cache-Control 'no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0';
        if_modified_since off;
        expires off;
        etag off;

        charset     utf-8;

        gzip on;
        gzip_proxied any;
        gzip_vary on;
        gzip_types application/javascript application/json text/css text/xml;
        gzip_comp_level 4;

        location ~ ^/apple-touch-icon {
            access_log off;
            log_not_found off;
            return 404;
        }

        location = /favicon.ico {
            access_log off;
            log_not_found off;
            return 404;
        }

        location = /robots.txt {
            access_log off;
            log_not_found off;
            return 404;

		}

		access_log /var/log/nginx/r2s.access.log;
        error_log /var/log/nginx/r2s.error.log;

        ssl_certificate /etc/letsencrypt/live/read2succeed.tk/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/read2succeed.tk/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
